#!/usr/bin/env bash

floaterm_win=$(xdotool search --class floaterm)

if [ -z $floaterm_win ]
then
  tmux has-session -t default && alacritty -o font.size=10 --class floaterm -e tmux attach -t default || alacritty -o font.size=10 --class floaterm -e tmux new -s default &
else
  i3-msg \[class="floaterm"\] scratchpad show
  i3-msg \[class="floaterm"\] move position center
fi


